Add PWA support, Service Worker and Manifest, plus icons.
evgeni/qifi pull request #18
Opened 2018-10-07 23:56 UTC by dalbitresb12

2018-10-09 18:49 UTC, evgeni commented
Thanks a ton! I'll have a closer look next week when I have some spare time, but this looks pretty polished already!

2020-03-01 22:30 UTC, dalbitresb12 commented
@evgeni, have you had time to review the pull request?

2020-03-08 08:33 UTC, evgeni requested changes
As a matter of fact I did, it didn't work and I totally forgot to contact you.

I've retried now and it works like a charm. Whatever happened last time. 🤷

Posted a few minor comments, would you like to address them, or shall I?

2020-03-08 08:33 UTC, evgeni commented on manifest.json
> +  "short_name": "QiFI",
QiFi, small I ;)

2020-03-08 08:33 UTC, evgeni commented on index.html
> +            console.log('SW not supported')
I don't think we need to spam the log in that case

2020-03-08 08:33 UTC, evgeni commented on sw.js
> +  'https://button.flattr.com/flattr-badge-large.png'
This is gone now

2020-03-08 12:34 UTC, dalbitresb12 commented
This pull request is using an older version of QiFi, should I do this again with the latest version available on GitHub?

2020-03-08 12:51 UTC, evgeni commented
Looking at the code, you only reference file names, those didn't change. So after merging it will automatically use the latest code.

2020-03-08 12:52 UTC, evgeni commented
Btw, you can see a deployed merge here: https://deploy-preview-18--qifi.netlify.com/

2020-03-10 23:25 UTC, dalbitresb12 commented
Is it okay now, @evgeni?
I'm kind of a newbie using Git, that's why I did two commits without noticing.

2020-03-10 23:34 UTC, dalbitresb12 commented
I've checked it and it's totally wrong, probably because I don't know how to use Git. I'll try to fix this. So sorry :(

2020-03-10 23:44 UTC, dalbitresb12 commented
I think this is now fixed. Sorry, I'm a total newbie using Git.

This still has conflicts in the index.html because I'm using an older commit.

2020-03-27 23:40 UTC, dalbitresb12 commented
@evgeni, have you checked the changes?

2020-03-28 11:43 UTC, evgeni commented
Yes, I did! Merging :)

2020-03-28 11:43 UTC, merged